# my_blockchain

TODO:

remove_block needs to print out "5: block doesn't exist" when removing a block that doesn't exist


find out why Removing last block causes segfault. Possibly related to sync_status_checker() and/or remove_block